### ISSUE TITLE
Improve Cards Styleguide

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/website-modus.trimble.com#745]
As a user of the design system, I want to know the guidelines for designing and developing dialogs to be consistent with other Trimble products.

**Comment by coliff** [comment]
> * Default cards in Modus Bootstrap don't have the border.
>   [modus-bootstrap.trimble.com/components/cards/#card-example](https://modus-bootstrap.trimble.com/components/cards/#card-example)

Default cards don't have border in Modus Bootstrap v1 but because they are widely used we can't really add them at this stage as it could be a sort of breaking change for users. Instead we will address this in the next major version (Modus Bootstrap v2): 
![image](https://github.com/trimble-oss/website-modus.trimble.com/assets/1212885/f3d449bc-2856-4e30-8906-de56de6ae1ee)

**Comment by coliff** [comment]
@enowak1031 - Can this issue be closed now? There are no instructions or guidelines to change the cards on the style guide.

**Comment by coliff** [comment]
ping @enowak1031 - Can this issue be closed now? There are no instructions or guidelines to change the cards on the style guide.

**Comment by coliff** [comment]
I added following changes:

- Update border-radius from 8px to 4px
- Update font-weight for card title to 600
- Update font-weight for card subtitle to 700

Closing issue now.
